### ISSUE TITLE
Error with missing "authors" field

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#124]
```
Exception happened during processing of request from ('192.168.200.103', 54358)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 616, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/app/devel-server.py", line 42, in __init__
    super().__init__(request, client_address, server, directory=server.args["theme_dir"])
  File "/usr/local/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/app/devel-server.py", line 237, in do_GET
    return function(self)
  File "/app/devel-server.py", line 110, in handle_puzzle
    obj = puzzle.package()
  File "/app/moth.py", line 401, in package
    'authors': self.get_authors(),
  File "/app/moth.py", line 387, in get_authors
    return self.authors or [self.author]
AttributeError: 'Puzzle' object has no attribute 'author'
```

**Comment by int00h5525** [comment]
Closed in #126
