### ISSUE TITLE
Handle files key in YAML puzzles

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#125]
```
INFO:moth:Puzzle is YAML-formatted
ERROR:root:Unrecognized header field: files
Traceback (most recent call last):
  File "/app/devel-server.py", line 153, in handle_mothballer
    mb = mothballer.package(category, catdir, self.seed)
  File "/app/mothballer.py", line 75, in package
    for puzzle in cat:
  File "/app/moth.py", line 460, in __iter__
    yield self.puzzle(points)
  File "/app/moth.py", line 455, in puzzle
    puzzle.read_directory(path)
  File "/app/moth.py", line 273, in read_directory
    self.read_stream(f)
  File "/app/moth.py", line 163, in read_stream
    self.read_yaml_header(stream)
  File "/app/moth.py", line 186, in read_yaml_header
    self.handle_header_key(key, value)
  File "/app/moth.py", line 259, in handle_header_key
    raise ValueError("Unrecognized header field: {}".format(key))
ValueError: Unrecognized header field: files
```

**Comment by int00h5525** [comment]
Closed in #127
