### ISSUE TITLE
devel server requires absolute path to puzzles sometimes

### ISSUE THREAD

**Issue by nealey** [dirtbags/moth#138]
```
Exception happened during processing of request from ('127.0.0.1', 60180)
Traceback (most recent call last):
  File "devel/devel-server.py", line 42, in __init__
    super().__init__(request, client_address, server, directory=server.args["theme_dir"])
TypeError: __init__() got an unexpected keyword argument 'directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 620, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "devel/devel-server.py", line 44, in __init__
    super().__init__(request, client_address, server)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "devel/devel-server.py", line 237, in do_GET
    return function(self)
  File "devel/devel-server.py", line 108, in handle_puzzle
    puzzle = self.get_puzzle()
  File "devel/devel-server.py", line 62, in get_puzzle
    puzzle = cat.puzzle(points)
  File "/home/user/Desktop/Moth_Spring_Cyberfire20/moth-master/devel/moth.py", line 450, in puzzle
    puzzle.read_directory(path)
  File "/home/user/Desktop/Moth_Spring_Cyberfire20/moth-master/devel/moth.py", line 268, in read_directory
    with pushd(path):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/user/Desktop/Moth_Spring_Cyberfire20/moth-master/devel/moth.py", line 35, in pushd
    os.chdir(newdir)
FileNotFoundError: [Errno 2] No such file or directory: '../../Moth_Fall_Cyberfire19/moth-master/malware-puzzles/01_setup/10'
----------------------------------------
127.0.0.1 - - [05/Mar/2020 16:30:10] "GET /random/sw.js HTTP/1.1" 200 -
^CTraceback (most recent call last):
  File "devel/devel-server.py", line 294, in <module>
    server.serve_forever()
  File "/usr/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

The fix for this appears to be providing an absolute path in the `--puzzles` argument.

**Comment by nealey** [comment]
The devel server has been completely rewritten and no longer has this problem. Instead, it has all new problems that we have yet to discover.
